# 銃撃戦プラグイン設定
## 設定を変更したら必ず /gwreload を実行してください。
## mysqlの設定を変更した場合はサーバーを再起動してください。

# Discord招待リンク
discord: 'https://discord.gg/w2jFt4vA5A'

# 権限設定
## 頭に :nanami-network:> と入力するとななみ鯖の権限システムになります。
## MySQLに接続ができなかった場合は、:nanami-networkになっていた場合でも強制的にデフォルト値に変更されます。
permission-setting: 'plugins/GunWar/permission/default.yml'

# ゲームの設定
game:
  # 自動でゲームを開始するかどうか。
  # デフォルトでは無効。
  auto-start: false
  # プレイするゲームモード。
  # NORMAL - 通常モード。チーム戦と個人戦がある
  # ZOMBIE_ESCAPE - ゾンビエスケープ。時間制限以内に逃走者を全員感染させるか、救助場所 (セーフエリア) にゾンビが入るとゾンビの勝利。
  # CASTLE_SIEGE - 攻城戦モード。守り側の大将を倒すと勝利。
  gamemode: 'normal'
  # 開始人数
  # デフォルト: 10人
  ## この人数に達すると自動的にゲームが開始されます。(無効化可能)
  required-players: 10
  # 準備時間 (秒)
  prepare: 10
  # デフォルト開始位置 (/setstartlocにて座標設定がされてない状態で、/startlocで座標指定がない場合または自動開始モードの場合に適用される)
  startloc:
    world: 'world'
    x: 0
    y: 0
    z: 0
  # ゾンビエスケープの設定
  zombie-escape:
    # ゾンビの割合 (10人いるうち何人選ばれるか)
    zombies: 3
    # ゾンビが選ばれるまでの時間 (秒)
    choose-zombies: 10
    # 救助が来るまでの時間 (制限時間 - 秒)
    game-time: 600
  # 通常モードの設定
  normal:
    # チーム戦の制限時間 - 秒
    game-time-team: 900
    # 個人戦の制限時間 - 秒
    game-time-solo: 900


# データベースの設定
mysql:
  host: 'localhost'
  port: 3306
  database: ''
  option: '?allowPublicKeyRetrieval=true&useSSL=false'
  password: ''

# デバッグモード
debug: false

# ここは変更しないでください
version: '1.7'