# GunWar plugin config
## PLEASE EXECUTE /gwreload COMMAND AFTER UPDATING CONFIG
## IF YOU CHANGE MySQL SETTING, YOU NEED TO RESTART THE SERVER

# Discord inviting url
discord: 'https://discord.gg/w2jFt4vA5A'

# permission setting
## if you enter :nanami-network:> at the beginning, permission mode will move to nanami-network permission system mode
## if the database cannot be connected, permission mode will move to normal permission system mode automatically
permission-setting: 'plugins/GunWar/permission/default.yml'

# setting for gun war gaming
game:
  # automatically start
  # this is disabled by default
  auto-start: false
  # game mode to play
  # NORMAL - normal mode. there are 2 modes, team and solo.
  # ZOMBIE_ESCAPE - zombie escape mode. zombies win if all survivors are infected or zombies enter the safe area within the time limit
  # CASTLE_SIEGE - castle siege mode. attackers win if the king of defenders team died.
  gamemode: 'normal'
  # players count to start game
  # DEFAULT: 10 players
  ## if auto-start is enabled, the game will be started automatically when players count reaches this value
  required-players: 10
  # prepare time (sec)
  prepare: 10
  # default starting location
  # (applies these values if the starting location is not specified using /setstartloc
  # and there are no location specified when the game started with /startloc command or if automatically starting mode is enabled)
  startloc:
    world: 'world'
    x: 0
    y: 0
    z: 0
  # setting for zombie escape
  zombie-escape:
    # zombie percentage (out of 10)
    zombies: 3
    # time to choose zombies (sec)
    choose-zombies: 10
    # gaming time after arriving safe area (time limit - sec)
    game-time: 180
  # setting for normal mode
  normal:
    # time limit for team mode - sec
    game-time-team: 900
    # tiem limit for solo mode - sec
    game-time-solo: 900


# setting for database
mysql:
  host: 'localhost'
  port: 3306
  database: ''
  option: '?allowPublicKeyRetrieval=true&useSSL=false'
  password: ''

# debugging mode
debug: false

# DO NOT CHANGE HERE
version: '2.1'